[PoC] Added Mojang protocol encryption based auth (take 2 lmao)
team-catgirl/collar pull request #49
Opened 2021-02-11 17:17 UTC by charlie353535

- Removed session verification
- Mojang encryption is now protocol enc based https://wiki.vg/index.php?title=Protocol_Encryption
- Tests ACTUALLY pass now :eyes:

2021-02-11 22:28 UTC, orsondmc requested changes
This is pretty close but some cleanup needs to occur before we can consider merging. 

I've left a few comments for you :) Thanks for this PR!

2021-02-11 22:28 UTC, orsondmc commented on client/src/main/java/team/catgirl/collar/client/Collar.java
> +                LOGGER.log(Level.INFO, "Starting session, I am "+configuration.username);
"Starting session for user " + configuration.username

2021-02-11 22:28 UTC, orsondmc commented on client/src/main/java/team/catgirl/collar/client/CollarConfiguration.java
> +        public String username;
`username` should be part of MinecraftSession

2021-02-11 22:28 UTC, orsondmc commented on client/src/main/java/team/catgirl/collar/client/CollarListener.java
> +    default void onMinecraftAccountVerificationFailed(Collar collar, String username) {};
session not username

2021-02-11 22:28 UTC, orsondmc commented on server/src/main/java/team/catgirl/collar/server/protocol/GroupsProtocolHandler.java
>  import team.catgirl.collar.server.CollarServer;
remove changes from this class. They are not relevant.

2021-02-11 22:28 UTC, orsondmc commented on server/src/main/java/team/catgirl/collar/server/services/groups/GroupService.java
>      private static final Logger LOGGER = Logger.getLogger(GroupService.class.getName());
revert changes

2021-02-11 22:28 UTC, orsondmc commented on server/src/main/java/team/catgirl/collar/server/session/SessionManager.java
> +
same here

2021-02-11 22:28 UTC, orsondmc commented on shared/src/main/java/team/catgirl/collar/protocol/session/FinishSessionHandshakeResponse.java
> +public class FinishSessionHandshakeResponse extends ProtocolResponse {
What does this Response do?

2021-02-11 22:28 UTC, orsondmc commented on shared/src/main/java/team/catgirl/collar/protocol/session/SessionFailedResponse.java
> +        @JsonProperty("username")
Should use session

2021-02-11 22:28 UTC, orsondmc commented on shared/src/main/java/team/catgirl/collar/security/mojang/AuthenticationJSON.java
> +class agent {
Change name to `Agent` as it is already lower case in `AuthenticationJSON` via `@JsonProperty`

2021-02-11 22:28 UTC, orsondmc commented on shared/src/main/java/team/catgirl/collar/security/mojang/AuthenticationJSON.java
> +public class AuthenticationJSON {
Change to `MojangAuthenticationRequest`

2021-02-11 22:28 UTC, orsondmc commented on shared/src/main/java/team/catgirl/collar/security/mojang/MinecraftPlayer.java
> +    public MinecraftPlayer(@JsonProperty("id") UUID id, @JsonProperty("server") String server, @JsonProperty("name") String name) {
the server should not be passing around the player name, only the UUID. Please remove this.

2021-02-11 22:28 UTC, orsondmc commented on shared/src/main/java/team/catgirl/collar/security/mojang/MinecraftProtocolEncryption.java
> +    public static String ROOT_DOMAIN = "mojang.com";
could this be base URL instead of root domain?

`baseUrl = 'http://authentication.mojang.com'` etc

2021-02-11 22:28 UTC, orsondmc commented on shared/src/main/java/team/catgirl/collar/security/mojang/MinecraftProtocolEncryption.java
> +                e.printStackTrace();
remove print

2021-02-11 22:28 UTC, orsondmc commented on shared/src/main/java/team/catgirl/collar/security/mojang/MinecraftProtocolEncryption.java
> +            e.printStackTrace();
remove print

2021-02-11 22:28 UTC, orsondmc commented on shared/src/main/java/team/catgirl/collar/security/mojang/MinecraftProtocolEncryption.java
> +    private static final OkHttpClient client = new OkHttpClient();
use `Util.http()` instead of constructing your own.

2021-02-11 22:28 UTC, orsondmc commented on shared/src/main/java/team/catgirl/collar/security/mojang/MinecraftProtocolEncryption.java
> +            = MediaType.get("application/json; charset=utf-8");
just create this inline instead of having it in memory forever

2021-02-11 22:28 UTC, orsondmc commented on shared/src/main/java/team/catgirl/collar/utils/Utils.java
> +    public static final KeyPair MINECRAFT_KEYPAIR;
Move to `ServerIdentityStore#getMinecraftKeyPair()` and persist it in `ServerIdentityKeyStore` when the server starts for the first time. Look at how `serverId` is stored in `ServerIdentityKeyStore`

2021-02-11 22:28 UTC, orsondmc commented on shared/src/test/java/team/catgirl/collar/security/mojang/MinecraftProtocolEncryptionTest.java
> +    static {
why is this static?

If you need to do this once per test make a method and annotate it with `@Before`

2021-02-11 22:28 UTC, orsondmc commented on shared/src/test/java/team/catgirl/collar/security/mojang/MinecraftProtocolEncryptionTest.java
> +            e.printStackTrace();
don't catch the exception, just let it go!

2021-02-11 22:28 UTC, orsondmc commented on shared/src/test/java/team/catgirl/collar/security/mojang/MinecraftProtocolEncryptionTest.java
> +            if (jsonNode.has("error")) {
you should do a if on the response.code() and map a real response object for the error case.

2021-02-11 22:28 UTC, orsondmc commented on shared/src/test/java/team/catgirl/collar/security/mojang/MinecraftProtocolEncryptionTest.java
> +/**
remove

2021-02-12 08:46 UTC, charlie353535 commented on shared/src/test/java/team/catgirl/collar/security/mojang/MinecraftProtocolEncryptionTest.java
> +            if (jsonNode.has("error")) {
it always returns a response, it sometimes returns an error with a 200 code.

2021-02-12 08:47 UTC, charlie353535 commented on shared/src/main/java/team/catgirl/collar/security/mojang/MinecraftPlayer.java
> +    public MinecraftPlayer(@JsonProperty("id") UUID id, @JsonProperty("server") String server, @JsonProperty("name") String name) {
That is needed for the protocol enc verification. It verifies by username, not UUID.

2021-02-12 08:47 UTC, charlie353535 commented on shared/src/main/java/team/catgirl/collar/protocol/session/SessionFailedResponse.java
> +        @JsonProperty("username")
Protocol encryption relies on names, not IDs

2021-02-12 08:49 UTC, charlie353535 commented on shared/src/main/java/team/catgirl/collar/protocol/session/FinishSessionHandshakeResponse.java
> +public class FinishSessionHandshakeResponse extends ProtocolResponse {
Tells the server that verification was successful

2021-02-12 08:51 UTC, orsondmc commented on shared/src/main/java/team/catgirl/collar/security/mojang/MinecraftPlayer.java
> +    public MinecraftPlayer(@JsonProperty("id") UUID id, @JsonProperty("server") String server, @JsonProperty("name") String name) {
that's reasonable then 👍

2021-02-12 08:51 UTC, orsondmc commented on server/src/main/java/team/catgirl/collar/server/CollarServer.java
> +            /*if (services.minecraftSessionVerifier.verify(request.session)) {
why is all this commented out? if its dead code delete it

2021-02-12 08:52 UTC, orsondmc commented on shared/src/main/java/team/catgirl/collar/security/mojang/MinecraftProtocolEncryption.java
> +                    .url("https://sessionserver."+ROOT_DOMAIN+"/session/minecraft/join")
We should probably embed a copy of https://github.com/team-catgirl/yggdrasil-mock and start it for testing

2021-02-12 10:05 UTC, charlie353535 commented
Think I got all changes

2021-02-12 10:11 UTC, orsondmc commented on server/src/main/java/team/catgirl/collar/server/security/mojang/MojangMinecraftSessionVerifier.java
>  public class MojangMinecraftSessionVerifier implements MinecraftSessionVerifier {
@charlie353535 lets delete all this verifier code and remove the dependency on OpenMCAuthenticator in `pom.xml` and `server/pom.xml`

2021-02-12 10:14 UTC, orsondmc commented on server/src/main/java/team/catgirl/collar/server/protocol/GroupsProtocolHandler.java
>  import team.catgirl.collar.server.CollarServer;
Revert this file

2021-02-12 10:15 UTC, orsondmc commented on shared/src/main/java/team/catgirl/collar/protocol/session/StartSessionResponse.java
> +
both members here must be `public final`

2021-02-12 10:16 UTC, orsondmc commented on shared/src/main/java/team/catgirl/collar/security/mojang/MinecraftSession.java
> +        return new MinecraftSession(id, "_", null,  serverIP);
why `_`? if there is no name, we should send `null`

2021-02-12 10:16 UTC, orsondmc commented on shared/src/main/java/team/catgirl/collar/security/mojang/MinecraftSession.java
> +    /*
delete the commented code

2021-02-12 10:16 UTC, orsondmc commented on shared/src/main/java/team/catgirl/collar/security/mojang/MojangAuthenticationRequest.java
> +public class MojangAuthenticationRequest {
all members should be `final`

2021-02-12 10:16 UTC, orsondmc commented on shared/src/main/java/team/catgirl/collar/security/mojang/MojangAuthenticationRequest.java
> +    public Agent agent_ = new Agent();
`agent` not `agent_`

2021-02-12 10:17 UTC, orsondmc commented on shared/src/main/java/team/catgirl/collar/security/mojang/MojangAuthenticationRequest.java
> +    public Agent(){}
make members `final`

2021-02-17 05:58 UTC, orsondmc commented
@charlie353535 I'm going to get to this as soon as I finish #53

2021-03-03 02:20 UTC, orsondmc commented
@charlie353535 Im doing some simplification of your work in https://github.com/team-catgirl/collar/pull/73

2021-03-03 02:20 UTC, closed without merging